# Generated by Django 3.2.5 on 2021-07-25 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(blank=True, max_length=300, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('DateOfBirth', models.DateField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(blank=True, max_length=200, null=True)),
                ('Stock', models.IntegerField()),
                ('Category', models.CharField(blank=True, max_length=200, null=True)),
                ('Price', models.IntegerField()),
                ('Description', models.CharField(blank=True, max_length=600, null=True)),
                ('Vegetarian', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('DateOrdered', models.DateField(auto_now_add=True)),
                ('OrderStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('CustomerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.customer')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.customer')),
                ('ProductID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.products')),
            ],
        ),
    ]
