# Generated by Django 3.2.5 on 2021-07-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
