# Generated by Django 3.2.5 on 2021-07-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_orders_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='OrderNumber',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
