# Generated by Django 3.2.5 on 2021-08-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_orders_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
