# Generated by Django 3.2.5 on 2021-08-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_orders_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ItemPrice',
            field=models.IntegerField(null=True),
        ),
    ]
