# Generated by Django 3.2.5 on 2021-09-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_orders_itemprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='DateOrdered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
