# Generated by Django 3.2.5 on 2021-09-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Qty',
            field=models.IntegerField(default=1),
        ),
    ]
