# Generated by Django 3.2.5 on 2021-10-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_orders_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
