# Generated by Django 3.2.5 on 2021-10-02 13:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Address',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
